config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("visualizador_cc.users.urls", namespace="users")),

    path("mapa/", include("visualizador_cc.mapa.urls", namespace="mapa")),

    path(
        "dashboard/", include("visualizador_cc.dashboard.urls", namespace="dashboard")
    ),
    path("reports/", include("visualizador_cc.reports.urls", namespace="reports")),
    path(
        "controls/",
        include("visualizador_cc.controls.urls", namespace="controls"),
    ),
    path(
        "indicadores/",
        include("visualizador_cc.indicadores.urls", namespace="indicadores"),
    ),
    path("noticias/", include("visualizador_cc.noticias.urls", namespace="noticias")),
    # Your stuff: custom urls includes go here
    path("ckeditor/", include("ckeditor_uploader.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
   
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

visualizador_cc/mapa/urls.py
from django.urls import path

from . import views

app_name = "mapa"
urlpatterns = [
    path('mapa_general/', views.MapaGeneral.as_view(), name='mapa_general'),
    path('mapa_general/<int:cueanexo>', views.DetalleEscuela.as_view(), name='detalle_escuela'),
    path('', views.Mapa.as_view(), name='index'),
    path('points/', views.Points.as_view(), name='points'),
    path('point_data/', views.PointData.as_view(),name='point_data'),
    path('search/', views.Search.as_view(), name='search'),
    path('filter/', views.Filter.as_view(),name='filter'),
    path('localizaciones_by_draw/', views.LocalizacionesByDraw.as_view(), name='localizaciones_by_draw'),
    path('localizaciones_by_draw_list/', views.LocalizacionesByDrawList.as_view(), name='localizaciones_by_draw_list'),
]

visualizador_cc/reports/urls.py
from unicodedata import name
from django.urls import path

from visualizador_cc.reports.views.matriculas import (
    ReportsMatricIndexView,
    ReportsMatricListView
)


from visualizador_cc.reports.viewsOLD import *



app_name = "reports"
urlpatterns = [
    path(
        "ReportsMatricIndexView",
        ReportsMatricIndexView.as_view(),
        name="ra_matricula_index",
    ),
    path(
        "ra_matricula_list/",
        ReportsMatricListView.as_view(),
        name="ra_matricula_list",
    ),
    path(
        "ReportLocalizacionesIndexView",
        ReportLocalizacionesIndexView.as_view(),
        name="ra_localizaciones_index"
    ),
    path(
        "ReportMatricAborigenIndexView",
        ReportMatricAborigenIndexView.as_view(),
        name="ra_matricula_aborigen"
    ),
    path(
        "ra_matricula_aborigen_list/",
        ReportMatricAborigenListView.as_view(),
        name="ra_matricula_aborigen_list"
    ),
    path(
        "ReportTrayectoriaIndexView",
        ReportTrayectoriaIndexView.as_view(),
        name="ra_trayectoria_index"
    ),
    path(
        "ra_trayectoria_list/",
        ReportTrayectoriaListView.as_view(),
        name="ra_trayectoria_list"
    ),
    path(
        "ReportDocenteActividadIndexView",
        ReportDocenteActividadIndexView.as_view(),
        name="ra_docentes_actividad_index"
    ),
    path(
        "ra_docentes_actividad_list/",
        ReportDocenteActividadListView.as_view(),
        name="ra_docentes_actividad_list"
    ),
    path(
        "ReportCargosIndexView",
        ReportCargosIndexView.as_view(),
        name="ra_cargos_index"
    ),
    path(
        "ra_cargos_list/",
        ReportCargosListView.as_view(),
        name="ra_cargos_list"
    ),

    path(
        'ra_cargos_options/',
         CargosOptionsList.as_view(),
         name='ra_cargos_options'
    ),

    path(
        "ReportSeccionesIndexView",
        ReportSeccionesIndexView.as_view(),
        name="ra_secciones_index"
    ),
    path(
        "ra_secciones_list/",
        ReportSeccionesListView.as_view(),
        name="ra_secciones_list"
    ),
    path(
        "ReportHorasIndexView",
        ReportHorasIndexView.as_view(),
        name="ra_horas_catedra_index"
    ),
    path(
        "ra_horas_catedra_list/",
        ReportHorasListView.as_view(),
        name="ra_horas_catedra_list"
    ),
    path(
        "ReportEgresadosIndexView",
        ReportEgresadosIndexView.as_view(),
        name="ra_egresados_index"
    ),
    path(
        "ra_egresados_list/",
        ReportEgresadosListView.as_view(),
        name="ra_egresados_list"
    ),
    path(
        "ReportJornadaIndexView",
        ReportJornadaIndexView.as_view(),
        name="ra_jornada_index"
    ),
    path(
        "ra_jornada_list/",
        ReportJornadaListView.as_view(),
        name="ra_jornada_list"
    )
]

visualizador_cc/users/urls.py
from django.urls import path

from visualizador_cc.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

visualizador_cc/indicadores/models.py
from django.db import models

# Create your models here.

visualizador_cc/controls/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
import pandas as pd

from visualizador_cc.controls.functions.controles import (
    MatriculaComunIncialControl,
    MatriculaComunPrimariaControl,
    MatriculaComunSecundariaControl
)


from visualizador_cc.controls.models import (
    ConMatricComunInicial,
    ConMatricComunPrimaria,
    ConMatricComunSecundaria
)
# Create your views here.


class ControlsMatriculaIndexView(View):
    def get(self, request):       
        context = {
            "title": "Control de Mátriculas - RA 2022",           
        }
        return render(request, "controls/matricula.html", context)
    


class ControlsMatriculaListView(ListView):

    def post(self, request, *args, **kwargs): 

        dt = request.POST      
        matricula_selected = dt.get("matricula_selected")    
        control_type_selected = dt.get("control_type_selected")     
        show_all = dt.get("show_all")

        print('matricula_selected', matricula_selected)
        print('control_type_selected', control_type_selected)
        print('show_all', show_all)

        if(matricula_selected == "none" or control_type_selected == "none"):            
            return JsonResponse({"data": []}, safe=False)    

        if(matricula_selected == "matricula_comun_inicial"):

            values = ConMatricComunInicial.objects.all().values()
            if not values.exists():              
                return JsonResponse({"data": []}, safe=False)  

            df = pd.DataFrame(values) 
        
            if(control_type_selected == "precocidad"): 
             
                df["control"] = df.apply(MatriculaComunIncialControl.precocidad, axis=1)  
             
            if(control_type_selected == "sobreedad"):

                df["control"] = df.apply(MatriculaComunIncialControl.sobreedad, axis=1)            
            
        if(matricula_selected == "matricula_comun_primaria"):

            values = ConMatricComunPrimaria.objects.all().values()
            if not values.exists():              
                return JsonResponse({"data": []}, safe=False)  

            df = pd.DataFrame(values) 
        
            if(control_type_selected == "precocidad"):
             
                df["control"] = df.apply(MatriculaComunPrimariaControl.precocidad, axis=1)    

            if(control_type_selected == "sobreedad"):           

                df["control"] = df.apply(MatriculaComunPrimariaControl.sobreedad, axis=1)                

            if(control_type_selected == "repitencia"):           

                df["control"] = df.apply(MatriculaComunPrimariaControl.repitencia, axis=1)                


        if(matricula_selected == "matricula_comun_secundaria"):

            values = ConMatricComunSecundaria.objects.all().values()
            if not values.exists():              
                return JsonResponse({"data": []}, safe=False)  

            df = pd.DataFrame(values) 
        
            if(control_type_selected == "precocidad"):                  
             
                df["control"] = df.apply(MatriculaComunSecundariaControl.precocidad, axis=1)  
                
            if(control_type_selected == "sobreedad"):

                df["control"] = df.apply(MatriculaComunSecundariaControl.sobreedad, axis=1)  


        if show_all == 'false':            
            data = df[df["control"] > 0].fillna(0).to_dict('records') 
        else:
            data = df.fillna(0).to_dict('records')  



        print('*****data', data)        
    
        return JsonResponse({                    
            "data": data                
        }, 
        safe=False)

visualizador_cc/corrections/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from visualizador_cc.users.models import User
from django.views.generic.list import ListView

from visualizador_cc.corrections.models import MatricComunInicial

# Create your views here.


class MatriculaIndexView(View):
    def get(self, request):
        context = {"title": "Mátricula"}
        return render(request, "corrections/matricula.html", context)


class MatricComunInicialListView(ListView):
    def post(self, request, *args, **kwargs):
        return JsonResponse(self._datatables(request), safe=False)

    def _datatables(self, request):

        dt = request.POST
        draw = int(dt.get("draw"))
        start = int(dt.get("start"))
        length = int(dt.get("length"))

        search = dt.get("search[value]")
        ra_selected = dt.get("ra_selected")

        if ra_selected == "-1":

            return {
                "draw": draw,
                "recordsTotal": 0,
                "recordsFiltered": 0,
                "data": [],
                "error_msg": "",
            }

        # if(TRUE):

        #     return {
        #         'draw': draw,
        #         'recordsTotal': 0,
        #         'recordsFiltered': 0,
        #         'data': [],
        #         'error_msg': "Un error"
        #     }

        total = MatricComunInicial.objects.using(ra_selected).all().count()
        filtered = total
        matriculasComunInicial = MatricComunInicial.objects.using(ra_selected).all()

        if search:
            matriculasComunInicial = MatricComunInicial.objects.using(ra_selected).filter(
                Q(escuela__icontains=search) | Q(cueanexo__icontains=search)
            )
            total = matriculasComunInicial.count()
            filtered = total

        # paginator
        paginator = Paginator(matriculasComunInicial, length)

        page_number = start / length + 1

        try:
            object_list = paginator.page(page_number).object_list
        except PageNotAnInteger:
            object_list = paginator.page(1).object_list
        except EmptyPage:
            object_list = paginator.page(1).object_list

        data = [
            {
                "cueanexo": loc.cueanexo,
                "id_fila": loc.id_fila,
                "escuela": loc.escuela,
                "sala": loc.sala,
                "turno": loc.turno,
                "nom_secc": loc.nom_secc,
                "tipo_secc": loc.tipo_secc,
                "total": loc.total,
                "total_var": loc.total_var,
                "menos_1_año": loc.menos_1_año,
                "un_año": loc.un_año,
                "dos_años": loc.dos_años,
                "tres_años": loc.tres_años,
                "cuatro_años": loc.cuatro_años,
                "cinco_años": loc.cinco_años,
                "seis_años": loc.seis_años,
                "total_disc": loc.total_disc,
                
            }
            for loc in object_list
        ]

        return {
            "draw": draw,
            "recordsTotal": total,
            "recordsFiltered": filtered,
            "data": data,
            "error_msg": "",
        }

visualizador_cc/indicadores/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

# Create your views here.



class CargosHorasView(TemplateView):
    template_name = "indicadores/cargos_horas.html"
    extra_context = { "title": "Cargos y horas 2021" }

class AnalisisComunInicialView(TemplateView):
    template_name = "indicadores/analisis_comun_inicial.html"
    extra_context = { "title": "Análsis Común Inicial 2021" }

visualizador_cc/reports/views/matriculas.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from visualizador_cc.reports.models import *

# Create your views here.

class ReportsMatricIndexView(View, LoginRequiredMixin):
    def get(self, request):
        context = {"title": "Reporte Matriculas"}
        return render(request, "reports/ra_matricula.html", context)


class ReportsMatricListView(ListView):

    def post(self, request, *args, **kwargs):

        dt = request.POST   
        matricula_selected = dt.get("matricula_selected")    
        ra_selected = dt.get("ra_selected")     

        print('matricula_selected', matricula_selected)
        print('control_type_selected', ra_selected)

        if(matricula_selected == "none" or ra_selected == "none"):            
            return JsonResponse({ "data": [] }, safe=False)    

        if(matricula_selected == 'matricula_comun_inicial'):
            object_list = RepMatricComunInicial.objects.using(ra_selected).all()

        if(matricula_selected == 'matricula_comun_primaria'):   
            object_list = RepMatricComunPrimaria.objects.using(ra_selected).all()

        if(matricula_selected == 'matricula_comun_secundaria'):   
            object_list = RepMatricComunSecundaria.objects.using(ra_selected).all()
                
        if(matricula_selected == 'matricula_comun_snu'): 
            object_list = RepMatricComunSnu.objects.using(ra_selected).all()

        if(matricula_selected == 'matricula_adultos_primaria'): 
            object_list = RepMatricAdultosPrimaria.objects.using(ra_selected).all()
        
        if(matricula_selected == 'matricula_adultos_secundaria'):          
            object_list = RepMatricAdultosSecundaria.objects.using(ra_selected).all()
        
        if(matricula_selected == 'matricula_especial_inicial'): 
            object_list = RepMatricEspecialInicial.objects.using(ra_selected).all()
        
        if(matricula_selected == 'matricula_especial_primaria'):
            object_list = RepMatricEspecialPrimaria.objects.using(ra_selected).all()
             
        data = []  
        for row in object_list:
            # print('parse', row.parse())
            data.append(row.parse())

        return JsonResponse({"data": data}, safe=False) 
        

visualizador_cc/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

visualizador_cc/templates/pages/about.html
{% extends "base.html" %}

visualizador_cc/templates/pages/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="mt-4 mb-4">
    
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://educacion.chaco.gob.ar/wp-content/uploads/2021/04/ministerio-educacion.jpg" class="d-block w-50 mx-auto altura-carrousel" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://guiaforestal.chaco.gov.ar/wsic2/img/nuevos%20logos%2002-01-20/chaco/logo_chaco_Color.png" class="d-block w-50 mx-auto altura-carrousel" alt="...">
            </div>
        
        </div>
    </div>
    
    <div id="tarjetas" class="row mt-4">
      <div class="wrapper">
        <div class="columnas">
                  <div class="columna" ontouchstart="this.classList.toggle('hover');">
                      <div class="contenedor">
                          <div class="front" style="background-image: url({% static 'images/tarjetas-index/mapa.png' %}); background-size: 250px; background-repeat: no-repeat">
                              <div class="inner">
                                  <h3></h3>
                    <span class="texto-lectura"></span>
                              </div>
                          </div>
                          <div class="back">
                              <div class="inner">
                                <a  href="{% url "mapa:mapa_general" %}" class="text-decoration-none"><p class="text-dark fw-light">Mapa interactivo de las distintas ofertas educativas</p></a>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="columna" ontouchstart="this.classList.toggle('hover');">
                    <div class="contenedor">
                        <div class="front" style="background-image: url({% static 'images/tarjetas-index/reportes.png' %}); background-size: 250px; background-repeat: no-repeat;">
                            <div class="inner">
                                <h3></h3>
                                    <span></span>
                            </div>
                        </div>
                        <div class="back">
                            <div class="inner">
                                <a href="{% url "dashboard:index" %}" class="text-decoration-none"><p class="text-dark fw-light">Reportes</p></a>
                            </div>
                        </div>
                    </div>
                </div>
                  <div class="columna" ontouchstart="this.classList.toggle('hover');">
                      <div class="contenedor">
                          <div class="front" style="background-image: url({% static 'images/tarjetas-index/indicadores.png' %}); background-size: 250px; background-repeat: no-repeat" >
                              <div class="inner">
                                    <h3></h3>
                                    <span></span>
                              </div>
                          </div>
                          <div class="back">
                              <div class="inner">
                                  <a href="#" class="text-decoration-none"><p class="text-dark fw-light">Indicadores estadisticos educativos para analisis.</p></a>
                              </div>
                          </div>
                      </div>
                    </div>        			
                    <div class="columna" ontouchstart="this.classList.toggle('hover');">
                        <div class="contenedor">
                            <div class="front" style="background-image: url({% static 'images/tarjetas-index/noticias.png' %}); background-size: 250px; background-repeat: no-repeat">
                                <div class="inner">
                                    <h3></h3>
                                        <span></span>
                                </div>
                            </div>
                            <div class="back">
                                <div class="inner">
                                    <a href="{% url "noticias:index" %}" class="text-decoration-none"><p class="text-dark fw-light">Información y noticias</p></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
            
       </div>

    </div>
  </section>



{% endblock %}

visualizador_cc/templates/pages/localizaciones.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<Style>
    table.dataTable td {
        font-size: 12px;
    }

    table tr.row-error {
        background-color: #ffa9a9;
    }

    table tr.row-warning {
        background-color: #fff1c5;
    }
</Style>

{% csrf_token %}


<input type="text" name="radio" id="radio" value="{{radio}}" class="d-none">
<input type="text" name="centro" id="centro" value="{{centro}}" class="d-none">


<div class="row justify-content-center container-table">
    <div class="col-12 pt-3 ">
        <table id="tabla-localizaciones" class="table table-bordered  " style="width: 100%;">
        </table>
    </div>
</div>

<div id="preloader" class="d-none">
    <div class='row justify-content-center'>
      <div class='col-auto'>
        <i class='fa-solid fa-cog fa-spin fa-xl'></i>
      </div>
      <div class='col-auto'>
        Obteniendo localizaciones seleccionadas.
      </div>
      <div class='col-auto'>
        Por favor espere...
      </div>
    </div>
  </div>

{% endblock %}

{% block inline_javascript %}

<script defer src="{% static 'js/mapa/localizaciones.js' %}"></script>

{% endblock %}

visualizador_cc/templates/pages/postear.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-8 my-3">
        <h1 class="text-center">Postear</h1>
        <form method="POST" enctype="multipart/form-data">
            {% load crispy_forms_tags %}
            {%csrf_token%}
            {{form.errors}} 
            {{form.media}} 
            {{ form|crispy }}
            <br>
            <input class="btn btn-primary" type="submit" value="Postear">
        </form>
    </div>
</div>

{% endblock content %}