config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("visualizador_cc.users.urls", namespace="users")),

    path("mapa/", include("visualizador_cc.mapa.urls", namespace="mapa")),

    path(
        "dashboard/", include("visualizador_cc.dashboard.urls", namespace="dashboard")
    ),
    path("reports/", include("visualizador_cc.reports.urls", namespace="reports")),
    path(
        "controls/",
        include("visualizador_cc.controls.urls", namespace="controls"),
    ),
    path(
        "indicadores/",
        include("visualizador_cc.indicadores.urls", namespace="indicadores"),
    ),
    path("noticias/", include("visualizador_cc.noticias.urls", namespace="noticias")),
    # Your stuff: custom urls includes go here
    path("ckeditor/", include("ckeditor_uploader.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
   
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

visualizador_cc/controls/urls.py
from django.urls import path

from visualizador_cc.controls.views import (
    ControlsMatriculaIndexView,
    ControlsMatriculaListView    
)
app_name = "controls"
urlpatterns = [
    path(
        "MatriculaIndexView",
        ControlsMatriculaIndexView.as_view(),
        name="matricula_index",
    ),
    path(
        "matricula_list/",
        ControlsMatriculaListView.as_view(),
        name="matricula_list",
    )
]

visualizador_cc/indicadores/urls.py
from django.urls import path

from visualizador_cc.indicadores.views import (
    CargosHorasView,
    AnalisisComunInicialView
)
app_name = "indicadores"
urlpatterns = [
    path(
        "cargos-horas",
        CargosHorasView.as_view(),
        name="cargos_horas",
    ),
    path(
        "analisis-comun-inical/",
        AnalisisComunInicialView.as_view(),
        name="analisis_comun_inical",
    )
]

visualizador_cc/mapa/urls.py
from django.urls import path

from . import views

app_name = "mapa"
urlpatterns = [
    path('mapa_general/', views.MapaGeneral.as_view(), name='mapa_general'),
    path('mapa_general/<int:cueanexo>', views.DetalleEscuela.as_view(), name='detalle_escuela'),
    path('', views.Mapa.as_view(), name='index'),
    path('points/', views.Points.as_view(), name='points'),
    path('point_data/', views.PointData.as_view(),name='point_data'),
    path('search/', views.Search.as_view(), name='search'),
    path('filter/', views.Filter.as_view(),name='filter'),
    path('localizaciones_by_draw/', views.LocalizacionesByDraw.as_view(), name='localizaciones_by_draw'),
    path('localizaciones_by_draw_list/', views.LocalizacionesByDrawList.as_view(), name='localizaciones_by_draw_list'),
]

visualizador_cc/reports/urls.py
from unicodedata import name
from django.urls import path

from visualizador_cc.reports.views.matriculas import (
    ReportsMatricIndexView,
    ReportsMatricListView
)


from visualizador_cc.reports.viewsOLD import *



app_name = "reports"
urlpatterns = [
    path(
        "ReportsMatricIndexView",
        ReportsMatricIndexView.as_view(),
        name="ra_matricula_index",
    ),
    path(
        "ra_matricula_list/",
        ReportsMatricListView.as_view(),
        name="ra_matricula_list",
    ),
    path(
        "ReportLocalizacionesIndexView",
        ReportLocalizacionesIndexView.as_view(),
        name="ra_localizaciones_index"
    ),
    path(
        "ReportMatricAborigenIndexView",
        ReportMatricAborigenIndexView.as_view(),
        name="ra_matricula_aborigen"
    ),
    path(
        "ra_matricula_aborigen_list/",
        ReportMatricAborigenListView.as_view(),
        name="ra_matricula_aborigen_list"
    ),
    path(
        "ReportTrayectoriaIndexView",
        ReportTrayectoriaIndexView.as_view(),
        name="ra_trayectoria_index"
    ),
    path(
        "ra_trayectoria_list/",
        ReportTrayectoriaListView.as_view(),
        name="ra_trayectoria_list"
    ),
    path(
        "ReportDocenteActividadIndexView",
        ReportDocenteActividadIndexView.as_view(),
        name="ra_docentes_actividad_index"
    ),
    path(
        "ra_docentes_actividad_list/",
        ReportDocenteActividadListView.as_view(),
        name="ra_docentes_actividad_list"
    ),
    path(
        "ReportCargosIndexView",
        ReportCargosIndexView.as_view(),
        name="ra_cargos_index"
    ),
    path(
        "ra_cargos_list/",
        ReportCargosListView.as_view(),
        name="ra_cargos_list"
    ),

    path(
        'ra_cargos_options/',
         CargosOptionsList.as_view(),
         name='ra_cargos_options'
    ),

    path(
        "ReportSeccionesIndexView",
        ReportSeccionesIndexView.as_view(),
        name="ra_secciones_index"
    ),
    path(
        "ra_secciones_list/",
        ReportSeccionesListView.as_view(),
        name="ra_secciones_list"
    ),
    path(
        "ReportHorasIndexView",
        ReportHorasIndexView.as_view(),
        name="ra_horas_catedra_index"
    ),
    path(
        "ra_horas_catedra_list/",
        ReportHorasListView.as_view(),
        name="ra_horas_catedra_list"
    ),
    path(
        "ReportEgresadosIndexView",
        ReportEgresadosIndexView.as_view(),
        name="ra_egresados_index"
    ),
    path(
        "ra_egresados_list/",
        ReportEgresadosListView.as_view(),
        name="ra_egresados_list"
    ),
    path(
        "ReportJornadaIndexView",
        ReportJornadaIndexView.as_view(),
        name="ra_jornada_index"
    ),
    path(
        "ra_jornada_list/",
        ReportJornadaListView.as_view(),
        name="ra_jornada_list"
    )
]

visualizador_cc/users/urls.py
from django.urls import path

from visualizador_cc.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

visualizador_cc/indicadores/models.py
from django.db import models

# Create your models here.

visualizador_cc/controls/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
import pandas as pd

from visualizador_cc.controls.functions.controles import (
    MatriculaComunIncialControl,
    MatriculaComunPrimariaControl,
    MatriculaComunSecundariaControl
)


from visualizador_cc.controls.models import (
    ConMatricComunInicial,
    ConMatricComunPrimaria,
    ConMatricComunSecundaria
)
# Create your views here.


class ControlsMatriculaIndexView(View):
    def get(self, request):       
        context = {
            "title": "Control de Mátriculas - RA 2022",           
        }
        return render(request, "controls/matricula.html", context)
    


class ControlsMatriculaListView(ListView):

    def post(self, request, *args, **kwargs): 

        dt = request.POST      
        matricula_selected = dt.get("matricula_selected")    
        control_type_selected = dt.get("control_type_selected")     
        show_all = dt.get("show_all")

        print('matricula_selected', matricula_selected)
        print('control_type_selected', control_type_selected)
        print('show_all', show_all)

        if(matricula_selected == "none" or control_type_selected == "none"):            
            return JsonResponse({"data": []}, safe=False)    

        if(matricula_selected == "matricula_comun_inicial"):

            values = ConMatricComunInicial.objects.all().values()
            if not values.exists():              
                return JsonResponse({"data": []}, safe=False)  

            df = pd.DataFrame(values) 
        
            if(control_type_selected == "precocidad"): 
             
                df["control"] = df.apply(MatriculaComunIncialControl.precocidad, axis=1)  
             
            if(control_type_selected == "sobreedad"):

                df["control"] = df.apply(MatriculaComunIncialControl.sobreedad, axis=1)            
            
        if(matricula_selected == "matricula_comun_primaria"):

            values = ConMatricComunPrimaria.objects.all().values()
            if not values.exists():              
                return JsonResponse({"data": []}, safe=False)  

            df = pd.DataFrame(values) 
        
            if(control_type_selected == "precocidad"):
             
                df["control"] = df.apply(MatriculaComunPrimariaControl.precocidad, axis=1)    

            if(control_type_selected == "sobreedad"):           

                df["control"] = df.apply(MatriculaComunPrimariaControl.sobreedad, axis=1)                

            if(control_type_selected == "repitencia"):           

                df["control"] = df.apply(MatriculaComunPrimariaControl.repitencia, axis=1)                


        if(matricula_selected == "matricula_comun_secundaria"):

            values = ConMatricComunSecundaria.objects.all().values()
            if not values.exists():              
                return JsonResponse({"data": []}, safe=False)  

            df = pd.DataFrame(values) 
        
            if(control_type_selected == "precocidad"):                  
             
                df["control"] = df.apply(MatriculaComunSecundariaControl.precocidad, axis=1)  
                
            if(control_type_selected == "sobreedad"):

                df["control"] = df.apply(MatriculaComunSecundariaControl.sobreedad, axis=1)  


        if show_all == 'false':            
            data = df[df["control"] > 0].fillna(0).to_dict('records') 
        else:
            data = df.fillna(0).to_dict('records')  



        print('*****data', data)        
    
        return JsonResponse({                    
            "data": data                
        }, 
        safe=False)

visualizador_cc/corrections/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from visualizador_cc.users.models import User
from django.views.generic.list import ListView

from visualizador_cc.corrections.models import MatricComunInicial

# Create your views here.


class MatriculaIndexView(View):
    def get(self, request):
        context = {"title": "Mátricula"}
        return render(request, "corrections/matricula.html", context)


class MatricComunInicialListView(ListView):
    def post(self, request, *args, **kwargs):
        return JsonResponse(self._datatables(request), safe=False)

    def _datatables(self, request):

        dt = request.POST
        draw = int(dt.get("draw"))
        start = int(dt.get("start"))
        length = int(dt.get("length"))

        search = dt.get("search[value]")
        ra_selected = dt.get("ra_selected")

        if ra_selected == "-1":

            return {
                "draw": draw,
                "recordsTotal": 0,
                "recordsFiltered": 0,
                "data": [],
                "error_msg": "",
            }

        # if(TRUE):

        #     return {
        #         'draw': draw,
        #         'recordsTotal': 0,
        #         'recordsFiltered': 0,
        #         'data': [],
        #         'error_msg': "Un error"
        #     }

        total = MatricComunInicial.objects.using(ra_selected).all().count()
        filtered = total
        matriculasComunInicial = MatricComunInicial.objects.using(ra_selected).all()

        if search:
            matriculasComunInicial = MatricComunInicial.objects.using(ra_selected).filter(
                Q(escuela__icontains=search) | Q(cueanexo__icontains=search)
            )
            total = matriculasComunInicial.count()
            filtered = total

        # paginator
        paginator = Paginator(matriculasComunInicial, length)

        page_number = start / length + 1

        try:
            object_list = paginator.page(page_number).object_list
        except PageNotAnInteger:
            object_list = paginator.page(1).object_list
        except EmptyPage:
            object_list = paginator.page(1).object_list

        data = [
            {
                "cueanexo": loc.cueanexo,
                "id_fila": loc.id_fila,
                "escuela": loc.escuela,
                "sala": loc.sala,
                "turno": loc.turno,
                "nom_secc": loc.nom_secc,
                "tipo_secc": loc.tipo_secc,
                "total": loc.total,
                "total_var": loc.total_var,
                "menos_1_año": loc.menos_1_año,
                "un_año": loc.un_año,
                "dos_años": loc.dos_años,
                "tres_años": loc.tres_años,
                "cuatro_años": loc.cuatro_años,
                "cinco_años": loc.cinco_años,
                "seis_años": loc.seis_años,
                "total_disc": loc.total_disc,
                
            }
            for loc in object_list
        ]

        return {
            "draw": draw,
            "recordsTotal": total,
            "recordsFiltered": filtered,
            "data": data,
            "error_msg": "",
        }

visualizador_cc/indicadores/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

# Create your views here.



class CargosHorasView(TemplateView):
    template_name = "indicadores/cargos_horas.html"
    extra_context = { "title": "Cargos y horas 2021" }

class AnalisisComunInicialView(TemplateView):
    template_name = "indicadores/analisis_comun_inicial.html"
    extra_context = { "title": "Análsis Común Inicial 2021" }

visualizador_cc/reports/views/matriculas.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from visualizador_cc.reports.models import *

# Create your views here.

class ReportsMatricIndexView(View, LoginRequiredMixin):
    def get(self, request):
        context = {"title": "Reporte Matriculas"}
        return render(request, "reports/ra_matricula.html", context)


class ReportsMatricListView(ListView):

    def post(self, request, *args, **kwargs):

        dt = request.POST   
        matricula_selected = dt.get("matricula_selected")    
        ra_selected = dt.get("ra_selected")     

        print('matricula_selected', matricula_selected)
        print('control_type_selected', ra_selected)

        if(matricula_selected == "none" or ra_selected == "none"):            
            return JsonResponse({ "data": [] }, safe=False)    

        if(matricula_selected == 'matricula_comun_inicial'):
            object_list = RepMatricComunInicial.objects.using(ra_selected).all()

        if(matricula_selected == 'matricula_comun_primaria'):   
            object_list = RepMatricComunPrimaria.objects.using(ra_selected).all()

        if(matricula_selected == 'matricula_comun_secundaria'):   
            object_list = RepMatricComunSecundaria.objects.using(ra_selected).all()
                
        if(matricula_selected == 'matricula_comun_snu'): 
            object_list = RepMatricComunSnu.objects.using(ra_selected).all()

        if(matricula_selected == 'matricula_adultos_primaria'): 
            object_list = RepMatricAdultosPrimaria.objects.using(ra_selected).all()
        
        if(matricula_selected == 'matricula_adultos_secundaria'):          
            object_list = RepMatricAdultosSecundaria.objects.using(ra_selected).all()
        
        if(matricula_selected == 'matricula_especial_inicial'): 
            object_list = RepMatricEspecialInicial.objects.using(ra_selected).all()
        
        if(matricula_selected == 'matricula_especial_primaria'):
            object_list = RepMatricEspecialPrimaria.objects.using(ra_selected).all()
             
        data = []  
        for row in object_list:
            # print('parse', row.parse())
            data.append(row.parse())

        return JsonResponse({"data": data}, safe=False) 
        

visualizador_cc/templates/layouts/header.html
{% load static %}


{% block css %}

<link href="{% static 'css/header.css' %}" rel="stylesheet">

{% endblock %}


{% block header %}


<div class="row border-bottom p-2 d-flex justify-content-between bg-light">




  <div class="d-flex align-item-center col-9 col-6 text-center">
    <span class="title h1">{{title}}</span>
  </div>


  <div class="col-3 d-flex justify-content-end">

    <div class="row align-item-center">
      <div class="col-8 text-end">
        <span class="me-2">{{ user.username }}</span>
      </div>
      <div class="col-4">

        <div class="dropdown text-end d-flex justify-content-center" >
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-user"></i>
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
            {% if request.user.username %}
            <li><a class="dropdown-item" href="{% url 'users:detail' request.user.username%}">Mi perfil</a></li>
            {% endif %}
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Salir</a></li>
          </ul>
        </div>

      </div>
    </div>



  </div>

</div>







{% endblock %}

{% block javascript %}

<script defer src="{% static 'js/header.js' %}"></script>

{% endblock %}

visualizador_cc/templates/layouts/sidebar.html
{% load static %}


{% block css %}

<link href="{% static 'css/sidebars.css' %}" rel="stylesheet">

{% endblock %}


{% block sidebar %}

<div id="menu" class="menu-dashboard flex-shrink-0 p-3 ps-1 text-white bg-dark">
  <a href="/" class="d-flex text-center align-items-center pb-3 mb-3 link-light text-decoration-none border-bottom">
    <!-- <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg> -->
    <i class="fa-solid fa-house fa-2x me-2 icon icon2"></i>
    <span class="fs-5 fw-semibold">Visualizador Estadísticas</span>
  </a>
  <ul class="list-unstyled ps-0">
    <li class="lista mb-1">
      <i class="fa-solid fa-location-dot icon"></i>
      <button class="btn btn-toggle collapsed w-100" data-bs-toggle="collapse" data-bs-target="#mapa-collapse" aria-expanded="false">
        Mapa
      </button>
      <div class="collapse" id="mapa-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'mapa:index' %}" class="link-light rounded w-75">Ver mapa</a></li>
        </ul>
      </div>
    </li>
    <li class="lista mb-1">
      <i class="fa-solid fa-table icon"></i>
      <button class="btn btn-toggle collapsed w-100" data-bs-toggle="collapse" data-bs-target="#reports-collapse" aria-expanded="false">
        Reportes
      </button>
      <div class="collapse" id="reports-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'reports:ra_localizaciones_index' %}" class="link-light rounded w-75 d-none">Localizaciones</a></li>
          <li><a href="{% url 'reports:ra_matricula_index' %}" class="link-light rounded w-75">Matrícula</a></li>
          <li><a href="{% url 'reports:ra_trayectoria_index' %}" class="link-light rounded w-75 d-none">Trayectoria</a></li>
          <li><a href="{% url 'reports:ra_docentes_actividad_index' %}" class="link-light rounded w-75">Docente en actividad</a></li>
          <li><a href="{% url 'reports:ra_cargos_index' %}" class="link-light rounded w-75">Cargos</a></li>
          <li><a href="{% url 'reports:ra_secciones_index' %}" class="link-light rounded w-75">Secciones</a></li>
          <li><a href="{% url 'reports:ra_horas_catedra_index' %}" class="link-light rounded w-75">Horas cátedras</a></li>
          <li><a href="#" class="link-light rounded w-75 d-none">Programas</a></li>
          <li><a href="{% url 'reports:ra_jornada_index' %}" class="link-light rounded w-75">Jornada completa ext.</a></li>
          <li><a href="{% url 'reports:ra_matricula_aborigen' %}" class="link-light rounded w-75">Matrícula aborigen</a></li>
          <li><a href="{% url 'reports:ra_egresados_index' %}" class="link-light rounded w-75">Egresados</a></li>
          <li><a href="#" class="link-light rounded w-75 d-none">Alum. s/sala 4</a></li>
          <li><a href="#" class="link-light rounded w-75 d-none">Alum. s/sala 5</a></li>
        </ul>
      </div>
    </li>
    <li class="lista mb-1 ">
      <i class="fa-solid fa-circle-exclamation icon"></i>
      <button class="btn btn-toggle collapsed w-100" data-bs-toggle="collapse" data-bs-target="#controls-collapse" aria-expanded="false">
        Controles
      </button>
      <div class="collapse" id="controls-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'controls:matricula_index' %}" class="link-light rounded w-75">Matrícula</a></li>
        </ul>
      </div>
    </li>
    <li class="lista mb-1">
      <i class="fa-solid fa-chart-pie icon"></i>
      <button class="btn btn-toggle collapsed w-100" data-bs-toggle="collapse" data-bs-target="#indicators-collapse" aria-expanded="false">
        Indicadores
      </button>
      <div class="collapse" id="indicators-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'indicadores:cargos_horas' %}" class="link-light rounded w-75">Horas y cargos</a></li>
          <li><a href="{% url 'indicadores:analisis_comun_inical' %}" class="link-light rounded w-75">Análisis común inicial</a></li>
        </ul>
      </div>
    </li>
    <li class="border-top my-3"></li>
    <li class="lista mb-1">
      <img class="icon image-icon" src="{% static 'images/favicons/LOGO_SIE.png' %}"></img>
      <button class="btn btn-toggle collapsed w-100" data-bs-toggle="collapse" data-bs-target="#sie-collapse" aria-expanded="false">
        SIE
      </button>
      <div class="collapse" id="sie-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li><a href="#" class="link-light rounded w-75">Modulo alumnos</a></li>
        </ul>
      </div>
    </li>
    <li class="mb-1 icon-arrow">
      <i class="fa-solid fa-angles-right"></i>
    </li>
  </ul>
</div>

{% comment %} MOBILE {% endcomment %}

<div id="menu-mobile" class="menu-dashboard-mobile flex-shrink-0 p-3 ps-1 text-white bg-dark">
  <a href="/" class="d-flex text-center align-items-center pb-3 mb-3 link-light text-decoration-none border-bottom">
    <!-- <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg> -->
    <i class="fa-solid fa-house fa-2x me-2"></i>
    <span class="fs-5 fw-semibold">Visualizador Estadísticas</span>
  </a>
  <ul class="list-unstyled ps-0">
    <li class="mb-1">
      
      <button class="btn btn-toggle2 collapsed w-100" data-bs-toggle="collapse" data-bs-target="#mapa-collapse" aria-expanded="false">
        Mapa
      </button>
      <div class="collapse" id="mapa-collapse">
        <ul class="btn-toggle-nav2 list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'mapa:index' %}" class="link-light rounded w-75">Ver mapa</a></li>
        </ul>
      </div>
    </li>
    <li class="mb-1">
      
      <button class="btn btn-toggle2 collapsed w-100" data-bs-toggle="collapse" data-bs-target="#reports-collapse" aria-expanded="false">
        Reportes
      </button>
      <div class="collapse" id="reports-collapse">
        <ul class="btn-toggle-nav2 list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'reports:ra_localizaciones_index' %}" class="link-light rounded w-75 d-none">Localizaciones</a></li>
          <li><a href="{% url 'reports:ra_matricula_index' %}" class="link-light rounded w-75">Matrícula</a></li>
          <li><a href="{% url 'reports:ra_trayectoria_index' %}" class="link-light rounded w-75 d-none">Trayectoria</a></li>
          <li><a href="{% url 'reports:ra_docentes_actividad_index' %}" class="link-light rounded w-75">Docente en actividad</a></li>
          <li><a href="{% url 'reports:ra_cargos_index' %}" class="link-light rounded w-75">Cargos</a></li>
          <li><a href="{% url 'reports:ra_secciones_index' %}" class="link-light rounded w-75">Secciones</a></li>
          <li><a href="{% url 'reports:ra_horas_catedra_index' %}" class="link-light rounded w-75">Horas cátedras</a></li>
          <li><a href="#" class="link-light rounded w-75 d-none">Programas</a></li>
          <li><a href="{% url 'reports:ra_jornada_index' %}" class="link-light rounded w-75">Jornada completa ext.</a></li>
          <li><a href="{% url 'reports:ra_matricula_aborigen' %}" class="link-light rounded w-75">Matrícula aborigen</a></li>
          <li><a href="{% url 'reports:ra_egresados_index' %}" class="link-light rounded w-75">Egresados</a></li>
          <li><a href="#" class="link-light rounded w-75 d-none">Alum. s/sala 4</a></li>
          <li><a href="#" class="link-light rounded w-75 d-none">Alum. s/sala 5</a></li>
        </ul>
      </div>
    </li>
    <li class="mb-1">
      
      <button class="btn btn-toggle2 collapsed w-100" data-bs-toggle="collapse" data-bs-target="#controls-collapse" aria-expanded="false">
        Controles
      </button>
      <div class="collapse" id="controls-collapse">
        <ul class="btn-toggle-nav2 list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'controls:matricula_index' %}" class="link-light rounded w-75">Matrícula</a></li>
        </ul>
      </div>
    </li>
    <li class="mb-1">
      
      <button class="btn btn-toggle2 collapsed w-100" data-bs-toggle="collapse" data-bs-target="#indicators-collapse" aria-expanded="false">
        Indicadores
      </button>
      <div class="collapse" id="indicators-collapse">
        <ul class="btn-toggle-nav2 list-unstyled fw-normal pb-1 small">
          <li><a href="{% url 'indicadores:cargos_horas' %}" class="link-light rounded w-75">Horas y cargos</a></li>
          <li><a href="{% url 'indicadores:analisis_comun_inical' %}" class="link-light rounded w-75">Análisis común inicial</a></li>
        </ul>
      </div>
    </li>
    <li class="border-top my-3"></li>
    <li class="mb-1">
      
      <button class="btn btn-toggle2 collapsed w-100" data-bs-toggle="collapse" data-bs-target="#sie-collapse" aria-expanded="false">
        SIE
      </button>
      <div class="collapse" id="sie-collapse">
        <ul class="btn-toggle-nav2 list-unstyled fw-normal pb-1 small">
          <li><a href="#" class="link-light rounded w-75">Modulo alumnos</a></li>
        </ul>
      </div>
    </li>
  </ul>
</div>
<span class="btn-menu">
  <i class="fa-solid fa-bars"></i>
</span>
<script defer src="{% static 'js/sidebars.js' %}"></script>
{% endblock %}

{% block javascript %}

<script defer src="{% static 'js/sidebars.js' %}"></script>

{% endblock %}